global using System.Diagnostics;
global using BadMC_Launcher.Services;
global using CommunityToolkit.Mvvm.ComponentModel;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Logging;
global using BadMC_Launcher.Extensions;
global using BadMC_Launcher.Utilities;
global using Microsoft.Windows.ApplicationModel.Resources;
